player playground changes
bitmovin/demos pull request #87
Opened 2022-05-24 06:03 UTC by kishorens

Features :-

- Support for testing various player and source configurations.
- Support for dynamically generating player and source configurations.

<img width="1251" alt="Screenshot 2022-05-24 at 11 26 38 AM" src="https://user-images.githubusercontent.com/66994293/169959303-41932bb4-7778-4d2d-8c3b-b3405ec50190.png">
<img width="1216" alt="Screenshot 2022-05-24 at 11 26 56 AM" src="https://user-images.githubusercontent.com/66994293/169959313-86f16462-1a7e-4afb-b83a-ed46d40f28e0.png">
<img width="1068" alt="Screenshot 2022-05-24 at 11 27 16 AM" src="https://user-images.githubusercontent.com/66994293/169959328-8f42d3e6-8251-4ec1-8775-34c427b1fca0.png">

2022-05-26 19:31 UTC, bitsmith1010 commented on player/player-playground/js/script.js
> +function intialize() {
replace "intialize" with "initialize"?

2022-05-26 20:01 UTC, bitsmith1010 requested changes
this is great! only minor comments, do you mind to separate the json objects such as `getPlayerSchema()` to separate files? also one minor type mistake (see comment)

2022-05-27 05:14 UTC, kishorens commented on player/player-playground/js/script.js
> +function intialize() {
Thanks, typo corrected

2022-05-27 05:47 UTC, kishorens commented
Thanks a lot for reviewing @bitsmith1010.
**Regarding separate files**:- The demo framework that we use for demos dynamically executes the files individually, so splitting the functions into different files is not possible with the existing setup.

2022-05-27 12:11 UTC, bitsmith1010 commented
I see.. it's surprising.. yes also the js files are not loaded from index.html load the script.. this could be something to look at in the demo framework in some time..

2022-05-27 13:19 UTC, bitsmith1010 approved these changes
Great!
possibly in the future to try more to divide the script to several files

2022-05-27 14:56 UTC, kishorens commented
Thanks @bitsmith1010 . Assigning the function to the window object worked, I separated the files and pushed the changes.

2022-05-27 20:05 UTC, bitsmith1010 approved these changes
@kishorens  now even better!

I see the CI deployed it in staging but the message is in the automated pull request https://github.com/bitmovin-engineering/demo-framework/pull/103 

tested the demo manually briefly and it looks good

2022-05-31 17:57 UTC, merged